name: run-gatling
description: Runs a Gatling test suite
inputs:
  javaVersion:
    description: "Java version to use"
    default: "17"
    required: true
  javaDistribution:
    description: "Java distribution to use"
    default: "microsoft"
    required: true
  testPath:
    description: "Path to the Gatling Test Suite"
    default: "./test/"
    required: true
  repoName:
    description: "Name of the repository to checkout ('org/repo')" 
  repoRef:
    description: "Tag, Branch, or Commit SHA for the Test Suite repository"
    default: "main"
  simulationClass:
    description: "Full classpath of the simulation to run"
runs:
  using: "composite"
  steps:
    - name: Checkout Test Suite if not local
      if: ${{ !hashFiles(inputs.testPath) }}
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repoName }}
        ref: ${{ inputs.repoRef }}
        path: ${{ inputs.testPath }}

    - name: Execute Gatling Test Suite
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.javaDistribution }}
        java-version: ${{ inputs.javaVersion }}
    - run: mvn -f ${{ inputs.testPath }} gatling:test ${{ inputs.simulationClass != '' && '-Dgatling.simulationClass=' || '' }}${{ inputs.simulationClass }}
      shell: bash

    # Download Gatling-Report to generate a parsable CSV file from the results
    - name: Download gatling-report
      env:
        GATLING_REPORT_VERSION: '5.0'
      run: wget https://maven-eu.nuxeo.org/nexus/service/local/artifact/maven/redirect?r=public-releases&g=org.nuxeo.tools&a=gatling-report&v=$GATLING_REPORT_VERSION&e=jar -O ./gatling-report.jar
      shell: bash

    - name: Generate CSV Report
      run: java -jar ./gatling-report.jar ./${{ inputs.testPath }}/target/gatling/$(cat ./lastRun.txt)/simulation.log)
      shell: bash

    - name: Generate Job Summary 
      uses: actions/github-script@v6
        with:
          script: require('./generateReport.js')
