name: run-gatling
description: Runs a Gatling test suite
inputs:
  javaVersion:
    description: "Java version to use"
    default: "17"
    required: true
  javaDistribution:
    description: "Java distribution to use"
    default: "microsoft"
    required: true
  testPath:
    description: "Path (or repo: 'org/repo') to your test suite"
    default: './test/'
    required: true
  repoName:
    description: "Name of the repository ('org/repo')" 
  repoRef:
    description: "Tag, branch or commit SHA for test suite repo"
  simulation:
    description: "Name of the simulation to run"
runs:
  using: "composite"
  steps:
    - name: Checkout Test Suite if not local
      if: ${{ !hashFiles(inputs.testPath) }}
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repoName }}
        ref: ${{ inputs.repoRef }}
        path: ${{ inputs.testPath }}

    - name: debug
      run: ls -la $GITHUB_WORKSPACE
      shell: bash

    - name: Execute Gatling Test Suite
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.javaDistribution }}
        java-version: ${{ inputs.javaVersion }}
    - run: mvn -f ${{ inputs.testPath }} gatling:test -D.simulation="${{ inputs.simulation }}"
      shell: bash